spring:
    application:
        name: Email-Sender

    mail:
        host: smtp.gmail.com
        port: 587
        username: elchibek.zh@gmail.com
        password: oomu ufzv anoc test
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        trust: smtp.gmail.com